runMax:
	python3 Simulator.py --no-drawJoints --hz=200 --velocityIterations=500 --positionIterations=100

runMaxNoDraw:
	python3 Simulator.py --no-drawJoints --no-drawShapes --hz=200 --velocityIterations=500 --positionIterations=100